# -*- coding: utf-8 -*-
"""Untitled64.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/18v0BBJea4Upq_RzC14knmO1OwP5l27Ig
"""

# Install streamlit if it's not already installed
!pip install streamlit

# Now you can import streamlit
import streamlit as st
import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt

# Setting gaya
st.set_page_config(page_title="Dashboard Bike Sharing", layout="wide")
sns.set(style="whitegrid")
plt.rcParams["figure.figsize"] = (10, 6)

# Judul
st.title("📊 Dashboard Bike Sharing Dataset")
st.markdown("Analisis data peminjaman sepeda harian berdasarkan kondisi cuaca dan waktu.")

# Load data
@st.cache_data
def load_data():
    df = pd.read_csv("main_data.csv")
    df['dteday'] = pd.to_datetime(df['dteday'])
    df['weather_label'] = df['weathersit'].map({
        1: 'Cerah/Berawan',
        2: 'Kabut/Cloudy',
        3: 'Hujan Ringan/Salju Ringan',
        4: 'Hujan Lebat/Snow+Fog'
    })
    return df

df = load_data()

# Sidebar filter
with st.sidebar:
    st.header("🔎 Filter")
    selected_season = st.multiselect(
        "Pilih Musim:",
        options=df['season'].unique(),
        default=df['season'].unique()
    )
    filtered_df = df[df['season'].isin(selected_season)]

# Tab visualisasi
tab1, tab2 = st.tabs(["📈 Cuaca vs Jumlah Peminjaman", "🕒 Peminjaman per Jam"])

with tab1:
    st.subheader("Distribusi Peminjaman Berdasarkan Cuaca")
    fig1, ax1 = plt.subplots()
    sns.boxplot(x='weather_label', y='cnt', data=filtered_df, ax=ax1, palette='Set2')
    ax1.set_xlabel("Kondisi Cuaca")
    ax1.set_ylabel("Jumlah Peminjaman")
    ax1.set_title("Pengaruh Cuaca terhadap Jumlah Peminjaman")
    st.pyplot(fig1)

with tab2:
    st.subheader("Rata-rata Jumlah Peminjaman per Jam")
    # Changed the file path from "../hour.csv" to "hour.csv"
    # assuming hour.csv is in the same directory as the script and main_data.csv
    hourly_avg = pd.read_csv("hour.csv").groupby('hr')['cnt'].mean()
    fig2, ax2 = plt.subplots()
    sns.lineplot(x=hourly_avg.index, y=hourly_avg.values, marker='o', ax=ax2)
    ax2.set_xlabel("Jam")
    ax2.set_ylabel("Rata-rata Peminjaman")
    ax2.set_title("Peminjaman Sepeda per Jam (Rata-rata)")
    st.pyplot(fig2)